/**
 * Created by xiejdm on 15-11-30.
 */
var fs = require('fs');

/**
 * Cause an error to be generated by trying to open a file that doesn’t exist.
 */
var stream = fs.createReadStream('not-found');

/**
 * Use the events API to attach an error handler.
 */
stream.on('error', function(err) {
  console.trace();
  console.error('Stack:', err.stack);
  console.error('The error raised was:', err);
});
